<template>
  <AppChassis active="me"><view class="px-4" style="padding-bottom:24px"><SubPageHeader back="/pages/learn/courses" />
    <view v-if="loading">正在加载课程…</view><view v-else-if="error"><text>{{ error }}</text><text class="block" style="margin-top:12px;color:var(--v5-brand)" @click="load">重试</text></view>
    <view v-else-if="course"><text class="block" style="font-size:20px;font-weight:600">{{ course.title }}</text><text class="block" style="margin-top:10px;color:var(--v5-ink-2)">{{ course.body }}</text><text class="block" style="margin-top:8px;color:var(--v5-ink-3)">版本 {{ course.version }} · 奖励 {{ course.rewardNex }} NEX</text><text v-if="course.sourceEnvironment === 'SANDBOX'" class="block" style="margin-top:6px;color:#b45309">{{ course.permanentLabel }} · Run {{ course.runId }} · {{ course.source }}/{{ course.sourceEnvironment }}</text>
      <view v-for="(question, index) in course.questions" :key="question.questionId" style="margin-top:16px"><text>{{ question.question }}</text><view v-for="(option, optionIndex) in question.options" :key="option" style="margin-top:8px" @click="answers[index] = optionIndex"><text>{{ answers[index] === optionIndex ? '●' : '○' }} {{ option }}</text></view></view>
      <text class="block" style="margin-top:20px;color:var(--v5-brand)" @click="finish">{{ submitting ? '提交中…' : (course.questions.length ? '提交测验' : '完成课程') }}</text><text v-if="result" class="block" style="margin-top:12px">{{ result.passed ? '已完成' : '未通过' }}<template v-if="result.rewardGranted"> · 已发放 {{ result.rewardNex }} NEX</template></text>
    </view>
  </view></AppChassis>
</template>
<script setup lang="ts">
import { computed, ref } from "vue";
import { onLoad } from "@dcloudio/uni-app";
import AppChassis from "@/components/app-chassis.vue";
import SubPageHeader from "@/components/sub-page-header.vue";
import { learningApi } from "@/api/learning-runtime";
import { remoteApiEnabled } from "@/api/runtime";
import { useLocaleStore } from "@/store/locale";
import type { LearningCourse, LearningResult } from "@/api/learning-api";
import { createSingleFlight } from "@/api/learning-submission";
import { sessionVault } from "@/api/runtime";
import { finishPendingLearningAttempt, pendingLearningAttemptKey, type LearningAttemptIdentity } from "@/api/learning-attempt-key";
const locale = useLocaleStore(); const courseId = ref(""); const course = ref<LearningCourse | null>(null); const result = ref<LearningResult | null>(null); const answers = ref<number[]>([]); const loading = ref(true); const submitting = ref(false); const error = ref("");
const language = computed(() => ["zh", "vi", "en"].includes(locale.code) ? locale.code : "zh");
function attemptIdentity(current: LearningCourse): LearningAttemptIdentity { const accountKey = sessionVault.read()?.user.userId; if (!accountKey) throw new Error("LEARNING_ATTEMPT_AUTH_REQUIRED"); return { accountKey: `user:${accountKey}`, courseId: current.id, version: current.version }; }
async function load() { loading.value = true; error.value = ""; course.value = null; if (!remoteApiEnabled || !courseId.value) { loading.value = false; error.value = "课程需要在受信任网络中获取；请返回教程中心后重试。"; return; } try { const displayed = await learningApi.course(courseId.value, language.value); const started = await learningApi.start(displayed.id, language.value, displayed.version); course.value = started; answers.value = Array(started.questions.length).fill(-1); } catch { error.value = "课程暂不可用；请重试。"; } finally { loading.value = false; } }
async function recoverAuthoritative(expectedVersion: string) { if (!course.value) return false; const fresh = await learningApi.course(course.value.id, language.value); course.value = fresh; if (!fresh.completed || fresh.version !== expectedVersion) return false; result.value = { courseId: fresh.id, version: fresh.version, score: fresh.lastScore, passed: true, completed: true, rewardGranted: fresh.rewardGranted, rewardNex: fresh.rewardGranted ? fresh.rewardNex : 0, attempts: fresh.attempts }; return true; }
const submitCourse = createSingleFlight(async () => { const current = course.value; if (!current) return null; const attempt = current.questions.length ? attemptIdentity(current) : null; const submitted = current.questions.length ? await learningApi.submitQuiz(current.id, current.version, answers.value, pendingLearningAttemptKey(attempt!)) : await learningApi.complete(current.id, current.version); if (submitted.courseId !== current.id || submitted.version !== current.version) throw new Error("LEARNING_COURSE_VERSION_CONFLICT"); if (attempt && (submitted.completed || !submitted.passed)) finishPendingLearningAttempt(attempt, pendingLearningAttemptKey(attempt)); return submitted; });
async function finish() { if (!course.value || loading.value || submitting.value) return; const expectedVersion = course.value.version; const current = course.value; const identity = current.questions.length ? attemptIdentity(current) : null; const attemptKey = identity ? pendingLearningAttemptKey(identity) : null; if (current.questions.length && answers.value.some((answer) => !Number.isSafeInteger(answer) || answer < 0)) { error.value = "请先完成全部题目后再提交。"; return; } submitting.value = true; error.value = ""; try { const submitted = await submitCourse(); if (submitted) { result.value = submitted; return; } if (!(await recoverAuthoritative(expectedVersion))) error.value = "提交结果尚未确认；已重新读取课程进度，奖励不会按本地状态显示。"; } catch { try { const receipt = identity && attemptKey ? await learningApi.quizReceipt(current.id, expectedVersion, attemptKey) : null; if (receipt?.committed && receipt.result) { result.value = receipt.result; if (!receipt.result.passed || receipt.result.completed) finishPendingLearningAttempt(identity!, attemptKey!); return; } if (await recoverAuthoritative(expectedVersion)) return; } catch {} error.value = "提交结果尚未确认；已重新读取课程进度，奖励不会按本地状态显示。"; } finally { submitting.value = false; } }
onLoad((options) => { courseId.value = typeof options?.id === "string" ? options.id : ""; void load(); });
</script>
