import type { ApiClient } from "./api-client";
import { ApiError } from "./errors";
import type { ApiEnvironment } from "./runtime-config";
import { matchesRuntimeProvenance } from "./runtime-provenance";

export interface DeveloperApiKey { id: number; keyId: string; name: string; prefix: string; last4: string; status: "ACTIVE" | "REVOKED"; source: "server"; sourceEnvironment: "SANDBOX" | "PRODUCTION"; runId: string; createdAt: string; revokedAt?: string; secret?: string }
export type DeveloperWebhookDeliveryStatus = "NOT_DELIVERED" | "PENDING" | "DELIVERING" | "RETRYING" | "SUCCEEDED" | "DEAD";
export interface DeveloperWebhook { id: number; name: string; url: string; events: string[]; status: "ACTIVE" | "DISABLED" | "DELETED"; deliveryStatus: DeveloperWebhookDeliveryStatus; deliveryEnabled: boolean; source: "server"; sourceEnvironment: "SANDBOX" | "PRODUCTION"; runId: string; createdAt: string; secret?: string }
export interface DeveloperWebhookDelivery { id: number; eventId: string; eventType: string; status: DeveloperWebhookDeliveryStatus; attemptCount: number; maxAttempts: number; lastStatusCode: number | null; lastError: string | null; nextRetryAt: string; createdAt: string; updatedAt: string }
export interface DeveloperResourcesApi {
  listKeys(): Promise<DeveloperApiKey[]>;
  revokeKey(id: number, idempotencyKey: string): Promise<DeveloperApiKey>;
  listWebhooks(): Promise<DeveloperWebhook[]>;
  createWebhook(input: { name: string; url: string; events: string[] }, idempotencyKey: string): Promise<DeveloperWebhook>;
  updateWebhook(id: number, input: { name: string; url: string; events: string[]; rotateSecret: boolean }, idempotencyKey: string): Promise<DeveloperWebhook>;
  deleteWebhook(id: number, idempotencyKey: string): Promise<void>;
  setWebhookEnabled(id: number, enabled: boolean, idempotencyKey: string): Promise<DeveloperWebhook>;
  listWebhookDeliveries(id: number): Promise<DeveloperWebhookDelivery[]>;
  rotateWebhookSecret(id: number, idempotencyKey: string): Promise<DeveloperWebhook>;
}
const EVENTS = new Set(["order.updated", "order.completed", "compute.job.completed", "compute.job.failed", "earnings.updated", "billing.invoice.created", "market.updated", "account.updated"]);
const DELIVERY_STATUSES = new Set<DeveloperWebhookDeliveryStatus>(["NOT_DELIVERED", "PENDING", "DELIVERING", "RETRYING", "SUCCEEDED", "DEAD"]);
function invalid(message = "DEVELOPER_RESOURCE_RESPONSE_INVALID"): never { throw new ApiError({ kind: "protocol", message }); }
function key(value: unknown, mode: ApiEnvironment): DeveloperApiKey { if (!value || typeof value !== "object" || Array.isArray(value)) return invalid(); const row = value as Record<string, unknown>; if (typeof row.id !== "number" || typeof row.keyId !== "string" || typeof row.name !== "string" || typeof row.prefix !== "string" || typeof row.last4 !== "string" || (row.status !== "ACTIVE" && row.status !== "REVOKED") || !matchesRuntimeProvenance(row, mode, "server") || typeof row.createdAt !== "string") return invalid(); return row as unknown as DeveloperApiKey; }
function webhook(value: unknown, mode: ApiEnvironment): DeveloperWebhook { if (!value || typeof value !== "object" || Array.isArray(value)) return invalid("DEVELOPER_WEBHOOK_RESPONSE_INVALID"); const row = value as Record<string, unknown>; if (typeof row.id !== "number" || typeof row.name !== "string" || typeof row.url !== "string" || !Array.isArray(row.events) || row.events.some((e) => typeof e !== "string" || !EVENTS.has(e)) || (row.status !== "ACTIVE" && row.status !== "DISABLED" && row.status !== "DELETED") || typeof row.deliveryStatus !== "string" || !DELIVERY_STATUSES.has(row.deliveryStatus as DeveloperWebhookDeliveryStatus) || typeof row.deliveryEnabled !== "boolean" || !matchesRuntimeProvenance(row, mode, "server") || typeof row.createdAt !== "string") return invalid("DEVELOPER_WEBHOOK_RESPONSE_INVALID"); return row as unknown as DeveloperWebhook; }
function delivery(value: unknown): DeveloperWebhookDelivery { if (!value || typeof value !== "object" || Array.isArray(value)) return invalid("DEVELOPER_WEBHOOK_DELIVERY_RESPONSE_INVALID"); const row = value as Record<string, unknown>; if (!Number.isSafeInteger(row.id) || typeof row.eventId !== "string" || !EVENTS.has(row.eventType as string) || typeof row.status !== "string" || !DELIVERY_STATUSES.has(row.status as DeveloperWebhookDeliveryStatus) || !Number.isSafeInteger(row.attemptCount) || (row.attemptCount as number) < 0 || !Number.isSafeInteger(row.maxAttempts) || (row.maxAttempts as number) < 1 || ((row.lastStatusCode !== null) && !Number.isSafeInteger(row.lastStatusCode)) || ((row.lastError !== null) && typeof row.lastError !== "string") || typeof row.nextRetryAt !== "string" || typeof row.createdAt !== "string" || typeof row.updatedAt !== "string") return invalid("DEVELOPER_WEBHOOK_DELIVERY_RESPONSE_INVALID"); return row as unknown as DeveloperWebhookDelivery; }
function deliveryPage(value: unknown): { items: DeveloperWebhookDelivery[]; hasMore: boolean; nextCursor: string | null } { if (!value || typeof value !== "object" || Array.isArray(value)) return invalid("DEVELOPER_WEBHOOK_DELIVERY_RESPONSE_INVALID"); const row = value as Record<string, unknown>; if (!Array.isArray(row.items) || typeof row.hasMore !== "boolean" || (row.nextCursor !== null && typeof row.nextCursor !== "string") || (row.hasMore && !(typeof row.nextCursor === "string" && /^\d+$/.test(row.nextCursor)))) return invalid("DEVELOPER_WEBHOOK_DELIVERY_RESPONSE_INVALID"); return { items: row.items.map(delivery), hasMore: row.hasMore, nextCursor: row.nextCursor as string | null }; }
export function createDeveloperResourcesApi(client: ApiClient, mode: ApiEnvironment = "prod"): DeveloperResourcesApi { return {
  async listKeys() { const value = await client.request<unknown>({ path: "/api/app/developer/api-keys" }); if (!Array.isArray(value)) return invalid(); return value.map(item => key(item, mode)); },
  async revokeKey(id, idempotencyKey) { return key(await client.request<unknown>({ path: `/api/app/developer/api-keys/${id}`, method: "DELETE", idempotencyKey }), mode); },
  async listWebhooks() { const value = await client.request<unknown>({ path: "/api/app/developer/webhooks" }); if (!Array.isArray(value)) return invalid("DEVELOPER_WEBHOOK_RESPONSE_INVALID"); return value.map(item => webhook(item, mode)); },
  async createWebhook(input, idempotencyKey) { return webhook(await client.request<unknown>({ path: "/api/app/developer/webhooks", method: "POST", body: { ...input, eventsJson: JSON.stringify(input.events) }, idempotencyKey }), mode); },
  async updateWebhook(id, input, idempotencyKey) { return webhook(await client.request<unknown>({ path: `/api/app/developer/webhooks/${id}`, method: "PUT", body: { ...input, eventsJson: JSON.stringify(input.events) }, idempotencyKey }), mode); },
  async deleteWebhook(id, idempotencyKey) { await client.request<unknown>({ path: `/api/app/developer/webhooks/${id}`, method: "DELETE", idempotencyKey }); },
  async setWebhookEnabled(id, enabled, idempotencyKey) { return webhook(await client.request<unknown>({ path: `/api/app/developer/webhooks/${id}/${enabled ? "enable" : "disable"}`, method: "POST", idempotencyKey }), mode); },
  async listWebhookDeliveries(id) { const rows: DeveloperWebhookDelivery[] = []; const ids = new Set<number>(); let cursor: string | null = null; for (let pageNo = 0; pageNo < 1000; pageNo += 1) { const suffix = cursor ? `&beforeId=${encodeURIComponent(cursor)}` : ""; const page = deliveryPage(await client.request<unknown>({ path: `/api/app/developer/webhooks/${id}/deliveries?limit=100${suffix}` })); for (const item of page.items) { if (ids.has(item.id)) return invalid("DEVELOPER_WEBHOOK_DELIVERY_PAGINATION_INVALID"); ids.add(item.id); rows.push(item); } if (!page.hasMore) return rows; if (!page.nextCursor || page.items.length === 0 || page.nextCursor === cursor) return invalid("DEVELOPER_WEBHOOK_DELIVERY_PAGINATION_INVALID"); cursor = page.nextCursor; } return invalid("DEVELOPER_WEBHOOK_DELIVERY_PAGINATION_INVALID"); },
  async rotateWebhookSecret(id, idempotencyKey) { return webhook(await client.request<unknown>({ path: `/api/app/developer/webhooks/${id}/rotate-secret`, method: "POST", idempotencyKey }), mode); },
}; }
