import type { ApiClient } from "./api-client";
import { ApiError } from "./errors";

export interface LegalTermsSection { key: string; title: string; body: string; sortOrder: number }
export interface LegalTermsCurrent { source: "server"; sourceEnvironment: "PRODUCTION" | "SANDBOX"; runId: string; requestedLocale: string; resolvedLocale: string; requestedJurisdiction: string; resolvedJurisdiction: string; provenance: string; version: string; effectiveAt: string; title: string; summary: string; sections: LegalTermsSection[]; acknowledged: boolean; acknowledgedAt: string | null }
function invalid(): never { throw new ApiError({ kind: "protocol", message: "LEGAL_TERMS_RESPONSE_INVALID" }); }
function object(value: unknown): Record<string, unknown> | null { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null; }
function text(value: unknown): string { if (typeof value !== "string" || !value.trim()) return invalid(); return value.trim(); }
function locale(value: unknown): string { const parsed = text(value); if (!/^[a-z]{2}(?:-[A-Z][A-Za-z0-9]{1,8})?$/.test(parsed)) return invalid(); return parsed; }
function jurisdiction(value: unknown): string { const parsed = text(value); if (!/^[A-Z][A-Z0-9_-]{1,15}$/.test(parsed)) return invalid(); return parsed; }
function version(value: unknown): string { const parsed = text(value); if (!/^v[1-9][0-9]{0,8}(?:\.[0-9]{1,8})*$/.test(parsed)) return invalid(); return parsed; }
function optionalText(value: unknown): string { if (value === null || value === undefined) return ""; if (typeof value !== "string") return invalid(); return value.trim(); }
function parse(value: unknown): LegalTermsCurrent { const row = object(value); if (!row || row.source !== "server" || (row.sourceEnvironment !== "PRODUCTION" && row.sourceEnvironment !== "SANDBOX") || typeof row.acknowledged !== "boolean") return invalid(); const sections = Array.isArray(row.sections) ? row.sections.map((entry) => { const item = object(entry); if (!item) return invalid(); return { key: text(item.key), title: text(item.title), body: text(item.body), sortOrder: Number(item.sortOrder) }; }) : invalid(); if (!sections.length || sections.some((s) => !Number.isSafeInteger(s.sortOrder) || s.sortOrder < 0)) return invalid(); const parsed: LegalTermsCurrent = { source: "server", sourceEnvironment: row.sourceEnvironment, runId: optionalText(row.runId), requestedLocale: locale(row.requestedLocale), resolvedLocale: locale(row.resolvedLocale), requestedJurisdiction: jurisdiction(row.requestedJurisdiction), resolvedJurisdiction: jurisdiction(row.resolvedJurisdiction), provenance: text(row.provenance), version: version(row.version), effectiveAt: text(row.effectiveAt), title: text(row.title), summary: text(row.summary), sections, acknowledged: row.acknowledged, acknowledgedAt: row.acknowledgedAt == null ? null : text(row.acknowledgedAt) }; if ((parsed.sourceEnvironment === "PRODUCTION" && parsed.runId !== "") || (parsed.sourceEnvironment === "SANDBOX" && !parsed.runId) || (parsed.acknowledged && !parsed.acknowledgedAt) || (!parsed.acknowledged && parsed.acknowledgedAt)) return invalid(); return parsed; }
export interface LegalTermsApi { current(locale: string, jurisdiction: string, authenticated?: boolean): Promise<LegalTermsCurrent>; acknowledge(snapshot: LegalTermsCurrent): Promise<LegalTermsCurrent> }
export function createLegalTermsApi(client: ApiClient): LegalTermsApi { return { current: async (locale, jurisdiction, authenticated = false) => parse(await client.request({ method: "GET", path: `/api/legal/terms/current?locale=${encodeURIComponent(locale)}&jurisdiction=${encodeURIComponent(jurisdiction)}`, authenticated })), acknowledge: async (snapshot) => parse(await client.request({ method: "POST", path: "/api/legal/terms/acknowledgment", authenticated: true, body: { locale: snapshot.resolvedLocale, jurisdiction: snapshot.resolvedJurisdiction, version: snapshot.version, confirmed: true, idempotencyKey: `terms-${snapshot.sourceEnvironment.toLowerCase()}-${snapshot.runId || "production"}-${snapshot.resolvedLocale}-${snapshot.resolvedJurisdiction}-${snapshot.version}`, runId: snapshot.runId } })) }; }
