import {describe,expect,it,vi} from 'vitest';
import {createPromotionApi,validatePromotionItems,PROMOTION_CAPABILITIES} from './promotion-api';
import type{ApiClient}from'./api-client';
import type{Quote,RewardDisclosure}from'./promotion-contracts';
const text={zh:'活动条款',en:'Promotion terms',vi:'Điều khoản chương trình'};
const disclosure:RewardDisclosure={title:text,terms:text,refundTerms:text,benefitDescription:text,deviceRights:null,deviceName:null};
const spec={rewardRuleId:'r1',beneficiaryRole:'BUYER' as const,type:'USDT' as const,calculation:'FIXED' as const,amount:'0.000001',assetPolicy:{policyId:'p1',version:1,contentHash:'hash'}};
const quote:Quote={quoteId:'quote-1',quoteHash:'hash',expiresAt:'2026-10-09T00:00:00Z',serverTime:'2026-10-08T00:00:00Z',itemCount:1,quantity:3,items:[{lineId:'l1',productNo:'sku-a',quantity:3,unitPriceUsdt:'0.000001',subtotalUsdt:'0.000003',discountUsdt:'0.000000',payableUsdt:'0.000003'}],subtotalUsdt:'0.000003',discountUsdt:'0.000000',amountUsdt:'0.000003',bundlePolicyVersion:1,activityId:'a1',activityVersion:1,eligibility:'ELIGIBLE',expectedRewards:[{lineId:'l1',activityId:'a1',version:1,ruleId:'rule',rewardRuleId:'r1',beneficiaryRole:'BUYER',groups:3,reward:spec,eligibility:'ELIGIBLE',message:null,disclosure}],warnings:[],reserved:false};
const receipt={orderNo:'o1',paymentStatus:'PENDING',orderStatus:'PENDING_PAYMENT',promotionQuoteId:'quote-1',quantity:3,payBy:'2026-10-09T00:00:00Z',rewards:quote.expectedRewards,amountUsdt:'0.000003',items:[{lineId:'l1',productNo:'sku-a',productName:'Frozen Alpha',quantity:3}]};
function setup(){const request=vi.fn();return{request,api:createPromotionApi({request}as unknown as ApiClient)};}
describe('promotion transport',()=>{
  it('requires frozen display names on promoted receipt lines and device disclosures',async()=>{
    const{api,request}=setup();request.mockResolvedValue({...receipt,items:[{lineId:'l1',productNo:'sku-a',quantity:3}]});await expect(api.findOrder('o1')).rejects.toThrow();
    request.mockResolvedValue({orders:[{...receipt,items:[{lineId:'l1',productNo:'sku-a',quantity:3}]}],nextCursor:null});await expect(api.findOrder('o1')).rejects.toThrow('PROMOTION_RESPONSE_INVALID');
    request.mockResolvedValue({...quote,expectedRewards:[{...quote.expectedRewards[0],reward:{rewardRuleId:'r1',type:'DEVICE',giftProductNo:'hidden',quantity:1,beneficiaryRole:'BUYER'},disclosure:{...disclosure,deviceName:null}}]});await expect(api.quote([{productNo:'sku-a',quantity:3}],'a1')).rejects.toThrow('PROMOTION_RESPONSE_INVALID');
  });
  it('quote requests carry distinct keys while order mutation keys stay caller-owned',async()=>{const{api,request}=setup();request.mockResolvedValue(quote);await api.quote([{productNo:'sku-a',quantity:3}],'a1');await api.quote([{productNo:'sku-a',quantity:3}],'a1');const keys=request.mock.calls.map(([r])=>r.idempotencyKey);expect(keys.every(k=>typeof k==='string'&&k.startsWith('promotion-quote-'))).toBe(true);expect(new Set(keys).size).toBe(2);});
  it('keeps exact money and quantity items, and declares all three capabilities',async()=>{const{api,request}=setup();request.mockResolvedValue(quote);expect((await api.quote([{productNo:'sku-a',quantity:3}],'a1')).amountUsdt).toBe('0.000003');expect(request.mock.calls[0][0].body).toEqual({items:[{productNo:'sku-a',quantity:3}],activityId:'a1',voucherId:null,clientCapabilities:PROMOTION_CAPABILITIES});});
  it('never expands quantity into repeated SKUs; accepts 8 distinct/100 units and rejects duplicates or overflow',()=>{expect(()=>validatePromotionItems(Array.from({length:8},(_,i)=>({productNo:'sku-'+i,quantity:i===0?93:1})))).not.toThrow();for(const items of [[{productNo:'x',quantity:1},{productNo:'x',quantity:1}],[{productNo:'x',quantity:101}],Array.from({length:9},(_,i)=>({productNo:String(i),quantity:1}))])expect(()=>validatePromotionItems(items)).toThrow();});
  it('bundle submits the exact same quote and string expected price through the original API',async()=>{const{api,request}=setup();request.mockResolvedValue(receipt);const bundle={...quote,items:[...quote.items,{...quote.items[0],lineId:'l2',productNo:'sku-b',quantity:1}]};await api.create(bundle,'original-key');expect(request).toHaveBeenCalledWith(expect.objectContaining({path:'/api/orders/bundle',idempotencyKey:'original-key',body:{items:[{productNo:'sku-a',quantity:3},{productNo:'sku-b',quantity:1}],policyVersion:1,expectedAmountUsdt:'0.000003',promotionQuoteId:'quote-1'}}));});
  it('rejects numerical money and incomplete immutable terms before any confirmation',async()=>{const{api,request}=setup();request.mockResolvedValue({...quote,amountUsdt:0.000003});await expect(api.quote([{productNo:'x',quantity:1}],'a1')).rejects.toThrow('PROMOTION_RESPONSE_INVALID');request.mockResolvedValue({...quote,expectedRewards:[{...quote.expectedRewards[0],disclosure:null}]});await expect(api.quote([{productNo:'x',quantity:1}],'a1')).rejects.toThrow();});
  it('recovery scans canonical order pages and never posts; rejects cursor cycles',async()=>{const{api,request}=setup();request.mockResolvedValueOnce({orders:[],nextCursor:'older'}).mockResolvedValueOnce({orders:[receipt],nextCursor:null});expect((await api.findOrder('o1'))?.orderNo).toBe('o1');expect(request.mock.calls.every(([r])=>!r.method)).toBe(true);request.mockResolvedValue({orders:[],nextCursor:'loop'});await expect(api.findOrder('absent')).rejects.toThrow();});
  it('a mismatched command target cannot supply another checkout receipt',async()=>{const{api,request}=setup();request.mockResolvedValue({idempotencyKey:'k',operation:'payOrder',targetId:'other',status:'SUCCEEDED',order:receipt});await expect(api.command('k','payOrder','o1')).rejects.toThrow();});
});
