<template>
  <view v-if="loading || activities.length || error || hasMore" class="promotion promotion-flat">
    <text class="promotion-title">{{ t.promotion.inviteTitle }}</text><text class="promotion-copy">{{ t.promotion.inviteNote }}</text>
    <text v-if="loading" class="promotion-copy" role="status">{{ t.promotion.loading }}</text>
    <view v-for="activity in activities" :key="activity.activityId" class="promotion-row"><view class="promotion-grow"><text style="display:block;font-weight:600">{{ localized(activity.title,locale.code) }}</text><template v-if="progress[activity.activityId]"><view class="promotion-summary"><text>{{ t.promotion.friendPaid }}</text><text>{{ progress[activity.activityId].qualifyingOrders }}</text></view><RewardRows :rewards="progress[activity.activityId].ownRewards" /></template><view class="promotion-link" role="button" tabindex="0" :aria-disabled="loading" @click="loadProgress(activity.activityId)"><text>{{ t.promotion.refresh }}</text></view></view></view>
    <text v-if="error" class="promotion-copy" role="alert">{{ t.promotion.error }}</text><text class="promotion-copy">{{ t.promotion.privacy }}</text>
    <view v-if="error" class="promotion-link" role="button" tabindex="0" :aria-disabled="loading" @click="loadActivities"><text>{{ t.promotion.retry }}</text></view>
    <view v-if="hasMore" class="promotion-link" role="button" tabindex="0" :aria-disabled="loading" @click="loadActivities"><text>{{ t.promotion.more }}</text></view>
    <view class="promotion-action primary" role="button" tabindex="0" @click="emit('share')"><text>{{ t.promotion.existingInvite }}</text></view>
  </view>
</template>
<script setup lang="ts">
import{ref,watch,onBeforeUnmount}from'vue';import{promotionApi,remoteApiEnabled}from'@/api/runtime';import type{PublicPromotion,ReferralProgress}from'@/api/promotion-contracts';import{useApp}from'@/store/app';import{useAuth}from'@/store/auth';import{useT}from'@/i18n/use-t';import{useLocaleStore}from'@/store/locale';import{localized}from'@/lib/promotion-display';import RewardRows from'./reward-rows.vue';
const emit=defineEmits<{(e:'share'):void}>(),t=useT(),app=useApp(),auth=useAuth(),locale=useLocaleStore();const activities=ref<PublicPromotion[]>([]),progress=ref<Record<string,ReferralProgress>>({}),loading=ref(false),error=ref(false),hasMore=ref(false);let cursor:string|null=null,generation=0,alive=true;
async function loadActivities(){if(!remoteApiEnabled||loading.value)return;const request=generation,account=app.accountKey,epoch=app.accountBindingEpoch;const current=()=>alive&&generation===request&&account===app.accountKey&&epoch===app.accountBindingEpoch;loading.value=true;error.value=false;try{const page=await promotionApi.list({cursor,limit:20},auth.isAuthenticated);if(!current())return;activities.value=[...new Map([...activities.value,...page.items.filter(p=>p.template==='DIRECT_REFERRAL')].map(activity=>[activity.activityId,activity])).values()];cursor=page.nextCursor;hasMore.value=page.hasMore;if(auth.isAuthenticated)for(const p of activities.value){if(!current())break;const result=await promotionApi.referral(p.activityId);if(current())progress.value={...progress.value,[p.activityId]:result};}}catch{if(current())error.value=true;}finally{if(current())loading.value=false;}}
async function loadProgress(id:string){if(!auth.isAuthenticated||loading.value)return;const request=generation,account=app.accountKey,epoch=app.accountBindingEpoch;const current=()=>alive&&request===generation&&account===app.accountKey&&epoch===app.accountBindingEpoch;loading.value=true;error.value=false;try{const result=await promotionApi.referral(id);if(current())progress.value={...progress.value,[id]:result};}catch{if(current())error.value=true;}finally{if(current())loading.value=false;}}
watch(()=>[app.accountKey,app.accountBindingEpoch],()=>{generation++;activities.value=[];progress.value={};cursor=null;loading.value=false;void loadActivities();},{immediate:true});onBeforeUnmount(()=>{alive=false;generation++;});
</script>
<style src="./promotion.css"></style>
