<template>
  <AppChassis active="me"><view class="promotion promotion-main">
    <view v-if="loading&&!reward" class="promotion-flat" role="status"><text>{{ p.loading }}</text></view>
    <view v-if="error" class="promotion-flat" role="alert"><text class="promotion-title">{{ p.error }}</text><view v-if="id" class="promotion-link" role="button" tabindex="0" @click="load"><text>{{ p.retry }}</text></view><view class="promotion-link" role="button" tabindex="0" @click="navTo('/pages/me/rewards-list?cat=promotion')"><text>{{ p.back }}</text></view></view>
    <template v-if="reward">
      <view class="promotion-flat"><text class="promotion-title">{{ localized(reward.disclosure.title,locale.code) }}</text><RewardRows :rewards="[reward]" :link-details="false" /><text class="promotion-copy">{{ displayDeadline(reward.updatedAt,locale.code) }}</text><view class="promotion-link" role="button" tabindex="0" :aria-disabled="loading" @click="load"><text>{{ p.refresh }}</text></view></view>
      <view class="promotion-flat"><text class="promotion-title">{{ p.rights }}</text><DisclosureDetails :disclosure="reward.disclosure" /></view>
      <view class="promotion-flat"><text class="promotion-title">{{ p.sourceOrder }}</text><text class="promotion-copy">{{ reward.orderNo }}</text><view v-if="reward.beneficiaryRole==='BUYER'" class="promotion-link" role="button" tabindex="0" @click="navTo('/pages/store/order-detail?id='+encodeURIComponent(reward.orderNo))"><text>{{ p.viewOrder }}</text></view></view>
      <view class="promotion-flat"><text class="promotion-title">{{ p.receipt }}</text><template v-if="reward.assetReceipt"><text v-for="instance in reward.assetReceipt.instanceNos" :key="instance" class="promotion-copy">{{ instance }}</text><text v-if="reward.assetReceipt.ledgerBizNo" class="promotion-copy">{{ reward.assetReceipt.ledgerBizNo }}</text><text v-if="reward.assetReceipt.issuedAt" class="promotion-copy">{{ displayDeadline(reward.assetReceipt.issuedAt,locale.code) }}</text><view v-if="!['REVERSED','CANCELLED'].includes(reward.state)" v-for="(deviceId,index) in reward.assetReceipt.deviceIds" :key="deviceId" class="promotion-link" role="button" tabindex="0" @click="navTo('/pages/earn/device-detail?id='+deviceId)"><text>{{ p.viewDevice }}</text> <text>{{ index+1 }}</text></view><view v-if="reward.assetReceipt.ledgerBizNo" class="promotion-link" role="button" tabindex="0" @click="navTo('/pages/me/wallet-bills?ledgerBizNo='+encodeURIComponent(reward.assetReceipt.ledgerBizNo))"><text>{{ p.viewBills }}</text></view></template><text v-else class="promotion-copy">{{ p.assetPending }}</text></view>
      <view v-if="progress" class="promotion-flat"><text class="promotion-title">{{ p.inviteTitle }}</text><view class="promotion-summary"><text>{{ p.friendPaid }}</text><text>{{ progress.qualifyingOrders }}</text></view><text class="promotion-copy">{{ p.privacy }}</text><view class="promotion-link" role="button" tabindex="0" @click="navTo('/team')"><text>{{ p.existingInvite }}</text></view></view>
    </template>
  </view></AppChassis>
</template>
<script setup lang="ts">
import{ref,computed,watch,onBeforeUnmount}from'vue';import{onLoad,onShow,onHide}from'@dcloudio/uni-app';import AppChassis from'@/components/app-chassis.vue';import RewardRows from'@/components/promotion/reward-rows.vue';import DisclosureDetails from'@/components/promotion/disclosure-details.vue';import{useT}from'@/i18n/use-t';import{useApp}from'@/store/app';import{useLocaleStore}from'@/store/locale';import{promotionApi}from'@/api/runtime';import type{Reward}from'@/api/promotion-api';import type{ReferralProgress}from'@/api/promotion-contracts';import{useSetPageHeader}from'@/composables/use-page-header';import{navTo,takeNavigationQuery}from'@/lib/route';import{localized,displayDeadline}from'@/lib/promotion-display';
const t=useT(),p=computed(()=>t.value.promotion),app=useApp(),locale=useLocaleStore();useSetPageHeader(()=>({title:p.value['reward-detail'],backHref:'/pages/me/rewards-list?cat=promotion'}));
const reward=ref<Reward|null>(null),progress=ref<ReferralProgress|null>(null),loading=ref(false),error=ref(false);let id='',generation=0,visible=true;
onLoad(options=>{const q=new URLSearchParams(takeNavigationQuery('/pages/events/promotion-reward-detail'));id=String(options?.obligationId??q.get('obligationId')??'').trim();void load();});
async function load(){if(!id){error.value=true;loading.value=false;return;}const request=++generation,account=app.accountKey,epoch=app.accountBindingEpoch;loading.value=true;error.value=false;const current=()=>visible&&request===generation&&account===app.accountKey&&epoch===app.accountBindingEpoch;try{const item=await promotionApi.reward(id);if(!current())return;reward.value=item;if(item.beneficiaryRole==='DIRECT_INVITER'){const value=await promotionApi.referral(item.activityId);if(current())progress.value=value;}}catch{if(current())error.value=true;}finally{if(current())loading.value=false;}}
watch(()=>[app.accountKey,app.accountBindingEpoch],()=>{generation++;reward.value=null;progress.value=null;void load();});onShow(()=>{visible=true;void load();});onHide(()=>{visible=false;generation++;loading.value=false;});onBeforeUnmount(()=>{visible=false;generation++;});
</script>
<style src="../../components/promotion/promotion.css"></style>
